# Generated by Django 6.1.2 on 2026-10-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evento',
            new_name='eventos_eve_data_in_3661d5_idx',
            old_name='eventos_eve_data_in_9c74b9_idx',
        ),
        migrations.RenameIndex(
            model_name='evento',
            new_name='eventos_eve_status_df7d7b_idx',
            old_name='eventos_eve_status_2f2165_idx',
        ),
        migrations.RenameIndex(
            model_name='evento',
            new_name='eventos_eve_cidade_0d2ad4_idx',
            old_name='eventos_eve_cidade_7fc251_idx',
        ),
    ]
